export const REFRESH_MENU = 'REFRESH_MENU';
export const REFRESH_NAVPATH = 'REFRESH_NAVPATH';
export const REFRESH_MENU_SUCCESS = 'REFRESH_MENU_SUCCESS';
export const REFRESH_MENU_FAILED = 'REFRESH_MENU_FAILED';
