// 查询菜单列表
export const MENU_LIST_SEARCH = 'MENU_LIST_SEARCH';
export const MENU_LIST_SEARCH_SUCCESS = 'MENU_LIST_SEARCH_SUCCESS';
export const MENU_LIST_SEARCH_FAILED = 'MENU_LIST_SEARCH_FAILED';

// 选中菜单列表项
export const MENU_ITEM_SELECTED = 'MENU_ITEM_SELECTED';
