export const STEP_FORM_STEP1 = 'STEP_FORM_STEP1';
export const STEP_FORM_STEP2 = 'STEP_FORM_STEP2';
export const STEP_FORM_SUBMIT = 'STEP_FORM_SUBMIT';
export const STEP_FORM_SUBMIT_SUCCESS = 'STEP_FORM_SUBMIT_SUCCESS';
export const STEP_FORM_SUBMIT_FAILED = 'STEP_FORM_SUBMIT_FAILED';

export const ADVANCED_FORM_POST = 'ADVANCED_FORM_POST';
export const ADVANCED_FORM_SUBMIT = 'ADVANCED_FORM_SUBMIT';
export const ADVANCED_FORM_SUBMIT_SUCCESS = 'ADVANCED_FORM_SUBMIT_SUCCESS';
export const ADVANCED_FORM_SUBMIT_FAILED = 'ADVANCED_FORM_SUBMIT_FAILED';
